CREATE TABLE decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_decks_name_not_blank
        CHECK (btrim(name) <> '')
);

CREATE INDEX idx_decks_name ON decks (name);
CREATE INDEX idx_decks_archived_at ON decks (archived_at);
