CREATE TABLE flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    term TEXT NOT NULL,
    definition TEXT NOT NULL,
    category VARCHAR(120),
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_flashcards_deck
        FOREIGN KEY (deck_id) REFERENCES decks (id),

    CONSTRAINT ck_flashcards_term_not_blank
        CHECK (btrim(term) <> ''),

    CONSTRAINT ck_flashcards_definition_not_blank
        CHECK (btrim(definition) <> ''),

    CONSTRAINT ck_flashcards_category_not_blank
        CHECK (category IS NULL OR btrim(category) <> ''),

    CONSTRAINT ck_flashcards_difficulty
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),

    CONSTRAINT ck_flashcards_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_flashcards_deck_status ON flashcards (deck_id, status);

CREATE UNIQUE INDEX ux_flashcards_deck_normalized_term
    ON flashcards (deck_id, lower(regexp_replace(btrim(term), '[[:space:]]+', ' ', 'g')));
