-- V3__create_practice_tables.sql

-- 1. Extend flashcards table with spaced repetition progress fields
ALTER TABLE flashcards
    ADD COLUMN correct_streak INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN next_review_date DATE,
    ADD COLUMN last_reviewed_at TIMESTAMP;

-- 2. Create practice_sessions table
CREATE TABLE practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    mode VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_cards INTEGER NOT NULL,
    completed_cards INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_practice_sessions_deck
        FOREIGN KEY (deck_id) REFERENCES decks (id),

    CONSTRAINT ck_practice_sessions_mode
        CHECK (mode IN ('FLASHCARDS')),

    CONSTRAINT ck_practice_sessions_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT ck_practice_sessions_completed_cards
        CHECK (completed_cards >= 0 AND completed_cards <= total_cards)
);

CREATE INDEX idx_practice_sessions_deck_status ON practice_sessions (deck_id, status);

-- 3. Create practice_session_cards table (Preserves snapshot state)
CREATE TABLE practice_session_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    flashcard_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    term_snapshot TEXT NOT NULL,
    definition_snapshot TEXT NOT NULL,
    category_snapshot VARCHAR(120),
    difficulty_snapshot VARCHAR(20) NOT NULL,
    answered BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_session_cards_session
        FOREIGN KEY (session_id) REFERENCES practice_sessions (id),
    CONSTRAINT fk_session_cards_flashcard
        FOREIGN KEY (flashcard_id) REFERENCES flashcards (id),

    CONSTRAINT ux_session_cards_session_position
        UNIQUE (session_id, position),
    CONSTRAINT ux_session_cards_session_flashcard
        UNIQUE (session_id, flashcard_id)
);

-- 4. Create practice_attempts table
CREATE TABLE practice_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_card_id BIGINT NOT NULL,
    result VARCHAR(20) NOT NULL,
    response_time_ms BIGINT,
    answered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_practice_attempts_card
        FOREIGN KEY (session_card_id) REFERENCES practice_session_cards (id),

    CONSTRAINT ck_practice_attempts_result
        CHECK (result IN ('INCORRECT', 'DIFFICULT', 'CORRECT', 'EASY')),

    CONSTRAINT ux_practice_attempts_card
        UNIQUE (session_card_id)
);
