CREATE TABLE generation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    deck_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    selected_page_from INTEGER NOT NULL,
    selected_page_to INTEGER NOT NULL,
    requested_card_count INTEGER NOT NULL,
    language VARCHAR(50) NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    raw_response TEXT,
    error_message TEXT,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_gen_runs_document FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_gen_runs_deck FOREIGN KEY (deck_id) REFERENCES decks(id),
    CONSTRAINT ck_gen_runs_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_gen_runs_pages CHECK (selected_page_from >= 1 AND selected_page_from <= selected_page_to),
    CONSTRAINT ck_gen_runs_card_count CHECK (requested_card_count > 0 AND requested_card_count <= 50)
);

CREATE INDEX idx_gen_runs_document_id ON generation_runs(document_id);
CREATE INDEX idx_gen_runs_deck_id ON generation_runs(deck_id);
CREATE INDEX idx_gen_runs_status ON generation_runs(status);
